---
name: "Feature request"
description: "Suggest an idea for this project"
labels: "feature-request"
body:
  - type: markdown
    attributes:
      value: Before you open a new feature request, search through the existing feature requests to see if others have had the same idea.
  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label: This issue is not a duplicate feature request of [previous feature requests](https://github.com/thenoctambulist/hass-airtouch/issues?q=is%3Aissue+label%3A%22feature-request%22+).
          required: true
        - label: This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
          required: true

  - type: textarea
    attributes:
      label: "Proposal"
      description: "A clear and concise description of your proposed feature."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Additional context"
      description: "Add any other context or screenshots about the feature request here."
