#
# Climate Services
#
set_hvac_mode_only:
  target:
    entity:
      integration: airtouch
      domain: climate
      device_class: ac # Not supported for zones
  fields:
    hvac_mode:
      required: true
      selector:
        select:
          options:
            - "cool"
            - "dry"
            - "fan_only"
            - "heat_cool"
            - "heat"
          translation_key: hvac_mode
#
# Time Services
#
clear_timer:
  target:
    entity:
      integration: airtouch
      domain: time
set_timer_from_delay:
  target:
    entity:
      integration: airtouch
      domain: time
  fields:
    delay:
      required: true
      selector:
        duration:
