name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  lint:
      uses: ./.github/workflows/lint.yml
  validate:
    uses: ./.github/workflows/validate.yml
  build:
    runs-on: ubuntu-latest
    needs: 
      - lint
      - validate
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set version number
        run: |
          version="${{ github.REF_NAME }}"
          # Strip the "v" prefix
          version=${version#v}
          sed -i "s/\"0.0.0\"/\"${version}\"/" custom_components/airtouch/manifest.json
      - name: Read filename
        id: read_filename
        run: |
          filename=$(jq .filename hacs.json -r)
          echo "filename=${filename}" >> $GITHUB_OUTPUT
      - name: ZIP Release
        uses: thedoctor0/zip-release@master
        with:
          directory: custom_components/airtouch
          type: "zip"
          filename: "../../${{ steps.read_filename.outputs.filename }}"
      - uses: ghalactic/github-release-from-tag@v5
        with:
          assets: |
            - path: "${{ steps.read_filename.outputs.filename }}"
